name: Python Unit Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
          pip install -r requirements.txt
          python3 -m pip install coverage
        
    - name: Run unit tests
      run: |
        cd tests/
        coverage run -m unittest discover -s . -v
    - name: Check Code Coverage
      run: |
        cd tests/
        coverage_report=$(coverage report -m)
        total_coverage=$(echo "$coverage_report" | grep "TOTAL" | awk '{print $NF}' | tr -d '%') # Usuwanie procentu
        echo "Całkowita procentowa pokrywalność kodu: $total_coverage%"
        if [ $total_coverage -lt 75 ]; then
          echo "Zbyt małe pokrycie kodu"
          exit 1
        fi
      shell: bash
